### ISSUE TITLE
Dictionary filter not working correctly for all use cases

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#58]

**Comment by surojitpakira** [comment]
Fixed and deployed

**Comment by kevinjscott** [comment]
I think this one still doesn't work correctly. For example, if I click the "H" box, it should open with just "H" in the filter field. But then from there, it should function exactly the same as if I had come to that screen via "see all." For example, if I change "H" to "Hub", I should see a result. Same thing if I change the "H" to "Network".

..Kev

**Comment by kevinjscott** [comment]
Currently, the "see all" view to the dictionary doesn't seem to allow any filtering at all i.e. typing anything into the filter field makes the list go blank.

**Comment by surojitpakira** [comment]
Completed and deployed
