### ISSUE TITLE
Intro screen content changes

### ISSUE THREAD

**Issue by kevinjscott** [scteisbe/sctemobile#88]
- [ ] Add Cortex brand logo to top of the intro screens (see below)
- [ ] Increase font size of the swipe text, make it blue, and change text to `Swipe to learn more`
- [ ] Change "Skip intro" text to "Get Started"

Card 1 text:
> Connect to technology with CORTEX Mobile.

> The SCTE/ISBE CORTEX Expert Development System enhances your learning by providing 24/7 access to technical information in the palm of your hand.

Layout:
![image](https://cloud.githubusercontent.com/assets/132882/17225598/9f4bb342-54d3-11e6-9dba-67f4d9d38c62.png)

Card 2 text:
> CORTEX delivers tech resources, industry apps and the latest content from SCTE/ISBE’s extensive course catalog at the moment of need on the job site.

Layout:
![image](https://cloud.githubusercontent.com/assets/132882/17225559/7e6473c6-54d3-11e6-908e-27f40c8670f0.png)

Card 3 text:
> Search for product docs and tech specs, access SCTE/ISBE’s resource library, and explore our on-the-job toolkit to improve your job performance.

Layout:
![image](https://cloud.githubusercontent.com/assets/132882/17225574/84893818-54d3-11e6-9ed5-b9eac98fc6e0.png)

Card 4:
> The SCTE/ISBE CORTEX Expert Development System follows your learning plans and tracks progress to guide you to become an expert and advance your career.

Layout:
![image](https://cloud.githubusercontent.com/assets/132882/17225581/89b91cf4-54d3-11e6-844f-482e7ece3ba7.png)

**Comment by surojitpakira** [comment]
fixed and deployed

**Comment by kevinjscott** [comment]
Reopening - see swipe item above.

**Comment by kevinjscott** [comment]
Still not quite right

![image](https://cloud.githubusercontent.com/assets/132882/17415911/d178df80-5a59-11e6-9088-dc657a6c20a5.png)

**Comment by kevinjscott** [comment]
Couple updates to last card...

![image](https://cloud.githubusercontent.com/assets/132882/17415989/2f67e4a6-5a5a-11e6-8439-f27d4c691b7e.png)

**Comment by kevinjscott** [comment]
Couple updates to last card...

![image](https://cloud.githubusercontent.com/assets/132882/17416011/47707ebe-5a5a-11e6-8ba5-0ccc86b861a5.png)

**Comment by surojitpakira** [comment]
Fixed and deployed
